/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.DonVIUDDao;
import DAO.LoaiSPDao;
import DAO.SanPhamDao;
import Entity.DonviDoUong;
import Entity.LoaiSP;
import Entity.SanPham;
import java.util.ArrayList;
import static java.util.Collections.list;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import BUL.SerSanPham;
import Entity.NhanVien;
import JDBCHelper.Auth;
import JDBCHelper.MsgBox;
import JDBCHelper.XImage;
import JDBCHelper.XImages;
import java.awt.Frame;
import java.io.File;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author HP
 */
public class QuanLySanPhamJPanel extends javax.swing.JPanel {

    SanPhamDao DAOSP = new SanPhamDao();
    LoaiSPDao daolsp = new LoaiSPDao();
    int row;
    DefaultTableModel model = new DefaultTableModel();
    DefaultTableModel modelspkd = new DefaultTableModel();

    /**
     * Creates new form QuanLySanPhamJPanel
     */
    public QuanLySanPhamJPanel() {
        initComponents();
        init();
        model = (DefaultTableModel) tblSanPhansd.getModel();

        filltotableSP();
        modelspkd = (DefaultTableModel) tblSanPHamksd.getModel();
        filltotableSPKD();
        //txtTenSP.setText("CÒN CÁI NỊT");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPhansd = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSanPHamksd = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cboLoaidouong = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        lblHinh = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboDonvi = new javax.swing.JComboBox<>();
        btnStart = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnnext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        rdoksd = new javax.swing.JRadioButton();
        rdosd = new javax.swing.JRadioButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        tbnLamMoi = new javax.swing.JButton();
        btndonvi = new javax.swing.JButton();
        btnloaidouong = new javax.swing.JButton();

        setBackground(new java.awt.Color(250, 182, 124));
        setLayout(null);

        tabs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabsMouseClicked(evt);
            }
        });

        tblSanPhansd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên sản phẩm ", "Loại đồ uống ", "Giá", "Đợn vị", "Trạng thái"
            }
        ));
        tblSanPhansd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhansdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPhansd);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1215, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );

        tabs.addTab("Sản Phẩm sử dụng", jPanel1);

        tblSanPHamksd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên sản phẩm", "Loại đồ uống ", "Giá", "Đợn vị", "Trạng thái"
            }
        ));
        tblSanPHamksd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPHamksdMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSanPHamksd);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1215, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );

        tabs.addTab("Sản Phẩm không sử dụng", jPanel2);

        add(tabs);
        tabs.setBounds(30, 100, 1220, 338);

        jPanel3.setBackground(new java.awt.Color(250, 182, 124));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Tìm kiếm(Tên hoặc Mã)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel3);
        jPanel3.setBounds(330, 20, 507, 66);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mã sản phẩm");
        add(jLabel2);
        jLabel2.setBounds(340, 500, 100, 17);

        txtMaSP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(txtMaSP);
        txtMaSP.setBounds(340, 520, 228, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tên sản phẩm");
        add(jLabel3);
        jLabel3.setBounds(340, 550, 120, 17);

        txtTenSP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTenSP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenSPKeyReleased(evt);
            }
        });
        add(txtTenSP);
        txtTenSP.setBounds(340, 580, 228, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Loại đồ uống");
        add(jLabel4);
        jLabel4.setBounds(340, 610, 110, 17);

        cboLoaidouong.setBackground(new java.awt.Color(227, 96, 5));
        cboLoaidouong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(cboLoaidouong);
        cboLoaidouong.setBounds(388, 640, 180, 30);

        jPanel4.setBackground(new java.awt.Color(227, 164, 114));

        lblHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHinh, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHinh, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );

        add(jPanel4);
        jPanel4.setBounds(27, 463, 244, 301);

        txtGia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(txtGia);
        txtGia.setBounds(688, 640, 230, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Giá");
        add(jLabel5);
        jLabel5.setBounds(690, 620, 60, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Đơn vị");
        add(jLabel6);
        jLabel6.setBounds(690, 490, 70, 17);

        cboDonvi.setBackground(new java.awt.Color(227, 96, 5));
        cboDonvi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(cboDonvi);
        cboDonvi.setBounds(738, 520, 180, 30);

        btnStart.setBackground(new java.awt.Color(255, 255, 255));
        btnStart.setText("|<");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        add(btnStart);
        btnStart.setBounds(470, 710, 61, 31);

        btnPrev.setBackground(new java.awt.Color(255, 255, 255));
        btnPrev.setText("<<");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        add(btnPrev);
        btnPrev.setBounds(560, 710, 61, 32);

        btnnext.setBackground(new java.awt.Color(255, 255, 255));
        btnnext.setText(">>");
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });
        add(btnnext);
        btnnext.setBounds(650, 710, 61, 34);

        btnLast.setBackground(new java.awt.Color(255, 255, 255));
        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        add(btnLast);
        btnLast.setBounds(740, 710, 61, 34);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Trạng thái");
        add(jLabel7);
        jLabel7.setBounds(690, 560, 100, 17);

        buttonGroup1.add(rdoksd);
        rdoksd.setText("Không sử dụng");
        add(rdoksd);
        rdoksd.setBounds(690, 580, 110, 23);

        buttonGroup1.add(rdosd);
        rdosd.setSelected(true);
        rdosd.setText("sử dụng");
        add(rdosd);
        rdosd.setBounds(810, 580, 90, 23);

        btnThem.setBackground(new java.awt.Color(255, 255, 255));
        btnThem.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBorder(null);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        add(btnThem);
        btnThem.setBounds(990, 470, 101, 34);

        btnXoa.setBackground(new java.awt.Color(255, 255, 255));
        btnXoa.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setBorder(null);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        add(btnXoa);
        btnXoa.setBounds(990, 590, 101, 34);

        btnSua.setBackground(new java.awt.Color(255, 255, 255));
        btnSua.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        add(btnSua);
        btnSua.setBounds(990, 530, 101, 34);

        tbnLamMoi.setBackground(new java.awt.Color(255, 255, 255));
        tbnLamMoi.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        tbnLamMoi.setText("Làm mới");
        tbnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnLamMoiActionPerformed(evt);
            }
        });
        add(tbnLamMoi);
        tbnLamMoi.setBounds(990, 660, 101, 34);

        btndonvi.setText("+");
        btndonvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndonviActionPerformed(evt);
            }
        });
        add(btndonvi);
        btndonvi.setBounds(340, 640, 41, 30);

        btnloaidouong.setText("+");
        btnloaidouong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloaidouongActionPerformed(evt);
            }
        });
        add(btnloaidouong);
        btnloaidouong.setBounds(684, 520, 50, 30);
    }// </editor-fold>//GEN-END:initComponents
NhanVien nvac = Auth.user;
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try {
            if (nvac.isVaiTro()) {
                insert();
            }else{
                JOptionPane.showMessageDialog(this, "Bạn không có quyền sử dụng chức năng này");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi liên hệ với Nam");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        try {
            if (nvac.isVaiTro()) {
                delete();
            }else{
                JOptionPane.showMessageDialog(this, "Bạn không có quyền sử dụng chức năng này");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi liên hệ với Nam");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        try {
            if (nvac.isVaiTro()) {
                update();
            }else{
                JOptionPane.showMessageDialog(this, "Bạn không có quyền sử dụng chức năng này");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi liên hệ với Nam");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tbnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnLamMoiActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_tbnLamMoiActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        row = 0;
        if (tabs.getSelectedIndex() == 0) {
            tblSanPhansd.setRowSelectionInterval(row, row);
            edit();
        } else {
            tblSanPHamksd.setRowSelectionInterval(row, row);
            editksd();
        }
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        if (tabs.getSelectedIndex() == 0) {
            if (row > 0) {
                row--;
                tblSanPhansd.setRowSelectionInterval(row, row);
                edit();
            }
        } else {
            if (row > 0) {
                row--;
                tblSanPHamksd.setRowSelectionInterval(row, row);
                editksd();
            }
        }
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        // TODO add your handling code here:
        if (tabs.getSelectedIndex() == 0) {
            if (row < tblSanPhansd.getRowCount() - 1) {
                row++;
                tblSanPhansd.setRowSelectionInterval(row, row);
                edit();
            }
        } else {
            if (row < tblSanPHamksd.getRowCount() - 1) {
                row++;
                tblSanPHamksd.setRowSelectionInterval(row, row);
                editksd();
            }
        }
    }//GEN-LAST:event_btnnextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        if (tabs.getSelectedIndex() == 0) {
            row = tblSanPhansd.getRowCount() - 1;

            tblSanPhansd.setRowSelectionInterval(row, row);
            edit();
        } else {
            row = tblSanPHamksd.getRowCount() - 1;
            tblSanPHamksd.setRowSelectionInterval(row, row);
            editksd();

        }
    }//GEN-LAST:event_btnLastActionPerformed

    private void tblSanPHamksdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPHamksdMouseClicked
        // TODO add your handling code here:
        try {
            row = tblSanPHamksd.getSelectedRow();
            editksd();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblSanPHamksdMouseClicked

    private void tblSanPhansdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhansdMouseClicked
        // TODO add your handling code here:
        try {
            row = tblSanPhansd.getSelectedRow();
            edit();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblSanPhansdMouseClicked

    private void tabsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabsMouseClicked
        // TODO add your handling code here:
        if (tabs.getSelectedIndex() == 1) {
            txtMaSP.setEditable(false);
            txtTenSP.setEditable(false);
            txtGia.setEditable(false);
            btnThem.setEnabled(false);
            btnXoa.setEnabled(false);
            cboLoaidouong.setEnabled(false);
            cboDonvi.setEnabled(false);

        } else {
            cboLoaidouong.setEnabled(true);
            cboDonvi.setEnabled(true);
            txtMaSP.setEditable(true);
            txtTenSP.setEditable(true);
            txtGia.setEditable(true);
            btnThem.setEnabled(true);
                       

        }
    }//GEN-LAST:event_tabsMouseClicked

    private void txtTenSPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenSPKeyReleased
        // TODO add your handling code here:
        CheckSPInuput();
    }//GEN-LAST:event_txtTenSPKeyReleased

    private void lblHinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhMouseClicked
        // TODO add your handling code here:
        chooseImages();
    }//GEN-LAST:event_lblHinhMouseClicked

    private void btndonviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndonviActionPerformed
        // TODO add your handling code here:
        new QLDOUongJDialog(null, true).setVisible(true);
        fillcomboboxLoaiSP();
    }//GEN-LAST:event_btndonviActionPerformed

    private void btnloaidouongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloaidouongActionPerformed
        // TODO add your handling code here:
        new QLDonVIDOUongJDialog(null, true).setVisible(true);
        fillcomboDonVi();
    }//GEN-LAST:event_btnloaidouongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btndonvi;
    private javax.swing.JButton btnloaidouong;
    private javax.swing.JButton btnnext;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboDonvi;
    private javax.swing.JComboBox<String> cboLoaidouong;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JRadioButton rdoksd;
    private javax.swing.JRadioButton rdosd;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblSanPHamksd;
    private javax.swing.JTable tblSanPhansd;
    private javax.swing.JButton tbnLamMoi;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
private void init() {
        fillcomboboxLoaiSP();
        fillcomboDonVi();
    }

    private void filltotableSP() {
        model.setRowCount(0);
        try {
            List<SanPham> list = DAOSP.selectAll();
            for (SanPham x : list) {
                model.addRow(new Object[]{x.getId_sp(), x.getTen_sp(), daolsp.selectNameByID(x.getId_loaiSP()),
                    x.getGia_sp(), daodv.selectNameByID(x.getId_donviSP()),
                    x.isTrangthai() ? "sử dụng" : "không sử dụng"});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void filltotableSPKD() {

        modelspkd.setRowCount(0);
        try {
            List<SanPham> list = DAOSP.select_Trangthai();
            for (SanPham x : list) {
                modelspkd.addRow(new Object[]{x.getId_sp(), x.getTen_sp(), daolsp.selectNameByID(x.getId_loaiSP()),
                    x.getGia_sp(), daodv.selectNameByID(x.getId_donviSP()),
                    x.isTrangthai() ? "sử dụng" : "không sử dụng"});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    LoaiSPDao dao = new LoaiSPDao();
    List<LoaiSP> listlsp;

    private void fillcomboboxLoaiSP() {
        DefaultComboBoxModel modelcbo = (DefaultComboBoxModel) cboLoaidouong.getModel();
        modelcbo.removeAllElements();
        listlsp = dao.selectll();
        for (LoaiSP loaiSP : listlsp) {
            modelcbo.addElement(loaiSP);
        }
    }
    DonVIUDDao daodv = new DonVIUDDao();
    List<DonviDoUong> listdv;

    private void fillcomboDonVi() {
        DefaultComboBoxModel modelDV = (DefaultComboBoxModel) cboDonvi.getModel();
        modelDV.removeAllElements();
        listdv = daodv.seleall();
        for (DonviDoUong donviDoUong : listdv) {
            modelDV.addElement(donviDoUong);
        }
    }

    private void chooseImages() {
        JFileChooser file = new JFileChooser();
        if (file.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File filechoser = file.getSelectedFile();
            XImages.save(filechoser);
            ImageIcon icon = XImages.read(filechoser.getName());
            lblHinh.setIcon(icon);
            lblHinh.setToolTipText(filechoser.getName());
            System.out.println(filechoser.getName());
            System.out.println(lblHinh.getToolTipText());
        }
    }

    private SanPham getInformation() {
        SanPham sp = new SanPham();
        sp.setId_sp(txtMaSP.getText());
        sp.setTen_sp(txtTenSP.getText());
        sp.setId_loaiSP(daolsp.selectIdByName(cboLoaidouong.getSelectedItem() + ""));
        sp.setGia_sp(Integer.parseInt(txtGia.getText()));
        sp.setTrangthai(rdosd.isSelected());
        sp.setId_donviSP(daodv.selectIDbyName(cboDonvi.getSelectedItem() + ""));
        sp.setHinh(lblHinh.getToolTipText());
        System.out.println(sp.getHinh());
        return sp;
    }

    private void setForm(SanPham sp) {
        String douong = tblSanPhansd.getValueAt(row, 2).toString();
        for (int i = 0; i < listlsp.size(); i++) {
            if (douong.equals(listlsp.get(i).getTenLoai())) {
                cboLoaidouong.setSelectedIndex(i);
            }
        }
        String donvidouong = tblSanPhansd.getValueAt(row, 4).toString();
        for (int i = 0; i < listdv.size(); i++) {
            if (donvidouong.equals(listdv.get(i).getTenDonvi())) {
                cboDonvi.setSelectedIndex(i);
            }
            txtMaSP.setText(sp.getId_sp());
            txtTenSP.setText(sp.getTen_sp());
//        cboLoaidouong.setSelectedItem(tblSanPhansd.getValueAt(row, 2).toString());
            txtGia.setText(sp.getGia_sp() + "");
            rdoksd.setSelected(!sp.isTrangthai());
            rdosd.setSelected(sp.isTrangthai());
            System.out.println(sp.getHinh());
            try {
                lblHinh.setToolTipText(sp.getHinh());
                lblHinh.setIcon((XImages.read(sp.getHinh())));
            } catch (Exception e) {
//            lblHinh.setIcon(new ImageIcon("unnamed.png"));
            }
        }
    }

    private void clearForm() {
        txtMaSP.setText("");
        txtTenSP.setText("");
        txtGia.setText("");
        lblHinh.setIcon(null);
        row = -1;
        identityMasp2();
        if (tabs.getSelectedIndex() == 0) {
            updateStatus();
        } else {
            updateStatus2();
        }
    }

    private void search() {
        if (tabs.getSelectedIndex() == 0) {
            String timkiem = txtTimKiem.getText();
            TableRowSorter<DefaultTableModel> sanpham = new TableRowSorter<>(model);
            tblSanPhansd.setRowSorter(sanpham);
            sanpham.setRowFilter(javax.swing.RowFilter.regexFilter(timkiem));
            tabs.setSelectedIndex(0);
        } else {
            String timkiem = txtTimKiem.getText();
            TableRowSorter<DefaultTableModel> sanpham = new TableRowSorter<>(modelspkd);
            tblSanPHamksd.setRowSorter(sanpham);
            sanpham.setRowFilter(javax.swing.RowFilter.regexFilter(timkiem));
            tabs.setSelectedIndex(1);
        }
    }

    private void edit() {
        String masp = tblSanPhansd.getValueAt(row, 0).toString();
        SanPham sp = DAOSP.selectID(masp);
        setForm(sp);
        updateStatus();
    }

    private void editksd() {
        String maspksd = tblSanPHamksd.getValueAt(row, 0).toString();
        SanPham sp = DAOSP.selectID(maspksd);
        setForm(sp);
        updateStatus2();

    }

    private boolean Checknull() {
        if (txtTenSP.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "tên sản phẩm không để trống");
            txtTenSP.requestFocus();

            return true;
        }
        List<SanPham> list = DAOSP.selectALLL();
        String id = txtMaSP.getText();
        String tensp = txtTenSP.getText();
        for (int i = 0; i < list.size(); i++) {
            if (id.equalsIgnoreCase(list.get(i).getId_sp())) {
                JOptionPane.showMessageDialog(this, "trùng khóa chính");
                txtMaSP.requestFocus();
                return true;
            } else if (tensp.equalsIgnoreCase(list.get(i).getTen_sp())) {
                JOptionPane.showMessageDialog(this, "tên sản phẩm đã tồn tại");
                txtTenSP.requestFocus();
                return true;
            }
        }
        if (txtGia.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "giá sản phẩm không để trống");
            txtGia.requestFocus();
            return true;
        } else if (lblHinh.getIcon() == null) {
            JOptionPane.showMessageDialog(this, "hình không được để trống");
            return true;
        } else if (txtMaSP.getText().length() < 3) {
            JOptionPane.showMessageDialog(this, "mã sản phẩm phải trên 2 kí tự");
            return true;
        } else if (txtTenSP.getText().length() < 5) {
            JOptionPane.showMessageDialog(this, "tên sản phẩm phải trên 5 kí tự");
            return true;
        }
        return false;

    }

    private boolean CheckNumber() {
        String regex = "SP\\d+";
        String regexx = "sp\\d+";
        Pattern parten = Pattern.compile(regex, Pattern.CASE_INSENSITIVE);
        if (!parten.matcher(txtMaSP.getText()).find()) {
            JOptionPane.showMessageDialog(this, "Nhập sai định dạng mã sản phẩm");
            return true;
        } else {
            Pattern p = Pattern.compile("^[0-9]{1,15}$");
            if (!p.matcher(txtGia.getText()).matches()) {
                JOptionPane.showMessageDialog(this, "nhập sai định dạng giá sản phẩm");
                return true;
            } else if (Integer.parseInt(txtGia.getText()) < 0) {
                JOptionPane.showMessageDialog(this, "giá nhập vào không được âm");
                return true;
            }
            return false;
        }
    }

    private boolean CheckSPInuput() {

        model.setRowCount(0);
        try {
            List<SanPham> list = DAOSP.Select_ByName(txtTenSP.getText());
            for (int i = 0; i < list.size(); i++) {
                model.addRow(new Object[]{list.get(i).getId_sp(), list.get(i).getTen_sp(),
                    daolsp.selectNameByID(list.get(i).getId_loaiSP()),
                    list.get(i).getGia_sp(), daodv.selectNameByID(list.get(i).getId_donviSP()),
                    list.get(i).isTrangthai() ? "sử dụng" : "không sử dụng"});
            }
        } catch (Exception e) {
        }
        return false;
    }
// capap nhap trang thai

    private void updateStatus() {
        boolean edit = (row >= 0);
        boolean fist = (row == 0);
        boolean last = (row == tblSanPhansd.getRowCount() - 1);
        ////
        txtMaSP.setEditable(!edit);
        btnThem.setEnabled(!edit);
        btnXoa.setEnabled(edit);
        btnSua.setEnabled(edit);
        ////
        btnStart.setEnabled(edit && !fist);
        btnPrev.setEnabled(edit && !fist);
        btnnext.setEnabled(!last && edit);
        btnLast.setEnabled(!last && edit);
    }

    private void insert() {
        if (Checknull()) {
            return;
        } else if (CheckNumber()) {
            return;
        } else if (CheckSPInuput()) {
            return;
        } else {
            try {
                if (MsgBox.confirm(this, "bạn có muốn thêm sản phẩm này ?")) {
                    SanPham sp = getInformation();
                    DAOSP.insert(sp);
                    if (tabs.getSelectedIndex() == 0) {
                        filltotableSP();
                        tabs.setSelectedIndex(0);
                    } else {
                        filltotableSPKD();
                        tabs.setSelectedIndex(1);
                    }
                    clearForm();
                    JOptionPane.showMessageDialog(this, "thêm mới thành công");
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "lỗi thêm dữ liệu");
            }

        }
    }

    private void update() {
        if (CheckNumber()) {
            return;
        } else {
            try {
                if (MsgBox.confirm(this, "bạn có muốn sửa sản phẩm ?")) {
                    SanPham sp = getInformation();
                    DAOSP.update(sp);
                    filltotableSP();
                    filltotableSPKD();
                    clearForm();
                    tabs.setSelectedIndex(0);
                    JOptionPane.showMessageDialog(this, "sửa thành thành công");
                }else;
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "sửa không thành công");
                e.printStackTrace();
            }

        }
    }

    private void delete() {
        try {
            int chon = JOptionPane.showConfirmDialog(this, "bạn có muốn xóa ?");
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "dữ liệu chưa được hiển thị để xóa");
                return;
            }
            if (chon == JOptionPane.YES_OPTION) {
                String manv = txtMaSP.getText();
                DAOSP.delete(manv);
                filltotableSPKD();
                filltotableSP();
                tabs.setSelectedIndex(1);
                clearForm();
                JOptionPane.showMessageDialog(this, "xóa thành công");
            }

        } catch (Exception e) {
            e.printStackTrace();
//            JOptionPane.showMessageDialog(this, "xóa không thành công");
        }
    }

    private void identityMasp2() {
        if (DAOSP.selectALLL().isEmpty()) {
            txtMaSP.setText("SP01");
        } else {
            txtMaSP.setText("SP" + (DAOSP.select_Max_id_java() + 1));
        }
    }

    private void updateStatus2() {
        boolean edit = (row >= 0);
        boolean fist = (row == 0);
        boolean last = (row == tblSanPHamksd.getRowCount() - 1);
        ////
        txtMaSP.setEditable(!edit);
        btnThem.setEnabled(!edit);
        btnXoa.setEnabled(!edit);
        btnSua.setEnabled(edit);
        ////
        btnStart.setEnabled(edit && !fist);
        btnPrev.setEnabled(edit && !fist);
        btnnext.setEnabled(!last && edit);
        btnLast.setEnabled(!last && edit);
    }

}
